[package]
name = "p8rs-piccolo"
description = "Stackless Lua VM implemented in pure Rust"
readme = "README.md"
version = "0.3.3"
edition = "2021"
authors = ["kyren <catherine@kyju.org>"]
license = "MIT"
repository.workspace = true

[dependencies]
ahash.workspace = true
allocator-api2.workspace = true
anyhow.workspace = true
gc-arena.workspace = true
hashbrown.workspace = true
thiserror.workspace = true
p8rs-macros.workspace = true
p8rs-types = { workspace = true, features = ["gc-arena"] }

rand = { workspace = true, optional = true }

[dev-dependencies]
clap = { version = "4.5", features = ["cargo"] }
rustyline = "14.0"

[features]
default = ["std", "rng"]
rng = ["dep:rand", "ahash/runtime-rng"]
std = ["rand?/std"]
