[package]
name = "p8rs-piccolo"
description = "Stackless Lua VM implemented in pure Rust"
readme = "README.md"
version = "0.3.3"
edition = "2021"
authors = ["kyren <catherine@kyju.org>"]
license = "MIT"
repository.workspace = true

[features]
default = ["std", "rng"]
rng = ["dep:rand", "ahash/runtime-rng"]
std = ["p8rs-log/std", "rand?/std"]
defmt = ["p8rs-log/defmt", "p8rs-types/defmt", "dep:defmt"]
log-04 = ["p8rs-log/log-04"]

[dependencies]
p8rs-types = { workspace = true, features = ["gc-arena"] }
p8rs-log.workspace = true
ahash.workspace = true
allocator-api2.workspace = true
anyhow.workspace = true
gc-arena.workspace = true
hashbrown.workspace = true
thiserror.workspace = true
p8rs-macros.workspace = true
arrayvec.workspace = true
defmt = { workspace = true, optional = true }
rand = { workspace = true, optional = true }
