[package]
name     = "p8rs-tests"
resolver = "3"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dev-dependencies]
p8rs = { workspace = true, features = ["log-04", "std"] }
p8rs-types.workspace = true
thiserror.workspace = true
colored = "3.0.0"
