[workspace]
resolver = "3"
members = [".", "iepass", "p8rs", "iepass-calib", "iepass-emu", "iepass", "p8rs-types", "p8rs-tests", "p8rs-piccolo", "p8rs-macros", "p8rs-log", "scripts"]

[workspace.package]
version = "0.1.0"
edition = "2024"
authors = ["Fun Maker <funmaker95@gmail.com>", "sebimoe <sebi@sebi.moe>"]
license = "MIT"
repository = "https://github.com/funmaker/iepass"
rust-version = "1.88.0"

[profile.dev]
# Rust debug is too slow.
# For debug builds always builds with some optimization
opt-level = "s"

[profile.release]
codegen-units    = 1     # LLVM can perform better optimizations using a single thread
debug            = 2
debug-assertions = false
incremental      = false
lto              = 'fat'
opt-level        = 's'
overflow-checks  = false

[workspace.dependencies]
p8rs = { path = "./p8rs", default-features = false }
p8rs-piccolo = { path = "./p8rs-piccolo", default-features = false }
p8rs-log = { path = "p8rs-log" }
p8rs-types = { path = "./p8rs-types" }
p8rs-macros = { path = "./p8rs-macros" }
p8rs-tests = { path = "./p8rs-tests" }
iepass = { path = "./iepass" }

embedded-io = { version = "0.7.1", features = ["alloc"] }
embedded-hal-async = "1.0.0"
defmt = { version = "1.0.1", features = ["alloc"] }
log-04 = { package = "log", version = "0.4.27" }
env_logger = "0.11.8"
anyhow = { version = "1.0.98", default-features = false }
esp-hal = { version = "1.0.0", features = ["defmt", "esp32s3", "unstable", "psram"] }
esp-alloc = { version = "0.9.0", features = ["defmt", "nightly"] }
esp-rtos = { version = "0.2.0", features = ["defmt", "esp32s3", "embassy", "esp-alloc"] }
esp-bootloader-esp-idf = { version = "0.4.0", features = ["defmt", "esp32s3"] }
embassy-executor = { version = "0.9.1", features = ["defmt"] }
embassy-time = { version = "0.5.0", features = ["defmt"] }
embassy-sync = { version = "0.7.2", features = ["defmt"] }
embassy-embedded-hal = { version = "0.5.0", features = ["defmt"] }
embassy-futures = { version = "0.1.2", features = ["defmt"] }
rtt-target = { version = "0.6.1", features = ["defmt"] }
panic-rtt-target = { version = "0.2.0", features = ["defmt"] }
bytemuck = { version = "1.24.0", features = ["derive", "min_const_generics", "extern_crate_alloc"] }
nb = { version = "1.1.0" }
ringbuffer = { version = "0.16.0", default-features = false }
pin-project = "1.1.10"
static_cell = "2.1.1"
bitflags = "2.9.4"
arrayvec = { version = "0.7.6", default-features = false }
thiserror = { version = "2.0", default-features = false }
ahash = { version = "0.8", default-features = false }
allocator-api2 = { version = "0.2.21", default-features = false, features = ["alloc"] }
gc-arena = { git = "https://github.com/kyren/gc-arena", rev = "4d526347a9b625c29e16f7165fd998615e51c52a", default-features = false, features = ["allocator-api2", "hashbrown"] }
hashbrown = { version = "0.14.5", features = ["raw"] }
rand = { version = "0.9", default-features = false, features = ["small_rng"] }

[patch.crates-io]
esp-hal                  = { git = "https://github.com/esp-rs/esp-hal.git", rev = "10025b6b26c07e482abf7ae7b6c1699a4c86b84e" }
esp-hal-procmacros       = { git = "https://github.com/esp-rs/esp-hal.git", rev = "10025b6b26c07e482abf7ae7b6c1699a4c86b84e" }
esp-rtos                 = { git = "https://github.com/esp-rs/esp-hal.git", rev = "10025b6b26c07e482abf7ae7b6c1699a4c86b84e" }
esp-rom-sys              = { git = "https://github.com/esp-rs/esp-hal.git", rev = "10025b6b26c07e482abf7ae7b6c1699a4c86b84e" }
esp-config               = { git = "https://github.com/esp-rs/esp-hal.git", rev = "10025b6b26c07e482abf7ae7b6c1699a4c86b84e" }
esp-sync                 = { git = "https://github.com/esp-rs/esp-hal.git", rev = "10025b6b26c07e482abf7ae7b6c1699a4c86b84e" }
esp-alloc                = { git = "https://github.com/esp-rs/esp-hal.git", rev = "10025b6b26c07e482abf7ae7b6c1699a4c86b84e" }
esp-bootloader-esp-idf   = { git = "https://github.com/esp-rs/esp-hal.git", rev = "10025b6b26c07e482abf7ae7b6c1699a4c86b84e" }
esp-metadata-generated   = { git = "https://github.com/esp-rs/esp-hal.git", rev = "10025b6b26c07e482abf7ae7b6c1699a4c86b84e" }
esp-riscv-rt             = { git = "https://github.com/esp-rs/esp-hal.git", rev = "10025b6b26c07e482abf7ae7b6c1699a4c86b84e" }
xtensa-lx                = { git = "https://github.com/esp-rs/esp-hal.git", rev = "10025b6b26c07e482abf7ae7b6c1699a4c86b84e" }
xtensa-lx-rt             = { git = "https://github.com/esp-rs/esp-hal.git", rev = "10025b6b26c07e482abf7ae7b6c1699a4c86b84e" }
xtensa-lx-rt-proc-macros = { git = "https://github.com/esp-rs/esp-hal.git", rev = "10025b6b26c07e482abf7ae7b6c1699a4c86b84e" }
