[workspace]
resolver = "3"
members = [".", "iepass", "iepass-core", "iepass-calib", "iepass-emu", "iepass"]

[profile.dev]
# Rust debug is too slow.
# For debug builds always builds with some optimization
opt-level = "s"

[profile.release]
codegen-units    = 1     # LLVM can perform better optimizations using a single thread
debug            = 2
debug-assertions = false
incremental      = false
lto              = 'fat'
opt-level        = 's'
overflow-checks  = false

[workspace.dependencies]
iepass-core = { path = "./iepass-core", default-features = false }
iepass = { path = "./iepass" }

embedded-io = { version = "0.6.1", features = ["alloc"] }
embedded-hal-async = "1.0.0"
defmt = { version = "1.0.1", features = ["alloc"] }
anyhow = { version = "1.0.98", default-features = false }
esp-bootloader-esp-idf = { version = "0.2.0", features = ["esp32s3"] }
esp-alloc = { version = "0.8.0", features = ["defmt", "nightly"] }
esp-hal = { version = "=1.0.0-rc.0", features = ["defmt", "esp32s3", "unstable", "psram"] }
esp-hal-embassy = { version = "0.9.0", features = ["defmt", "esp32s3"] }
embassy-executor = { version = "0.9.1", features = ["defmt"] }
embassy-time = { version = "0.4.0", features = ["defmt"] }
embassy-sync = { version = "0.7.2", features = ["defmt"] }
embassy-embedded-hal = { version = "0.5.0", features = ["defmt"] }
embassy-futures = { version = "0.1.2", features = ["defmt"] }
rtt-target = { version = "0.6.1", features = ["defmt"] }
panic-rtt-target = { version = "0.2.0", features = ["defmt"] }
nb = { version = "1.1.0" }
ringbuffer = { version = "0.16.0", default-features = false }
pin-project = "1.1.10"
static_cell = "2.1.1"
micromath = "2.1.0"
piccolo = { git = "https://github.com/funmaker/piccolo-nostd.git", rev = "437c8ffe7808f0080557ad5e5a718915b60c00ed", default-features = false }

[patch.crates-io]
esp-hal                  = { git = "https://github.com/funmaker/esp-hal.git" }
esp-hal-procmacros       = { git = "https://github.com/funmaker/esp-hal.git" }
esp-hal-embassy          = { git = "https://github.com/funmaker/esp-hal.git" }
esp-rom-sys              = { git = "https://github.com/funmaker/esp-hal.git" }
esp-config               = { git = "https://github.com/funmaker/esp-hal.git" }
esp-metadata             = { git = "https://github.com/funmaker/esp-hal.git" }
esp-metadata-generated   = { git = "https://github.com/funmaker/esp-hal.git" }
esp-riscv-rt             = { git = "https://github.com/funmaker/esp-hal.git" }
xtensa-lx                = { git = "https://github.com/funmaker/esp-hal.git" }
xtensa-lx-rt             = { git = "https://github.com/funmaker/esp-hal.git" }
xtensa-lx-rt-proc-macros = { git = "https://github.com/funmaker/esp-hal.git" }
