[config]
skip_core_tasks = true
default_to_workspace = false


# Scripts
[tasks.rle-encode]
extend = "script-base"
script = { file = "./scripts/rle_encode.rs" }


# Testing
[tasks.test]
command = "cargo"
args = ["test", "--workspace", "--exclude", "iepass", "--exclude", "iepass-calib", "${@}"]


# Running
[tasks.flash]
dependencies = ["build-assets"]
cwd = "./iepass"
env.RUSTUP_TOOLCHAIN = "esp"
command = "cargo"
args = ["run", "${@}"]

[tasks.flash-calib]
dependencies = ["build-assets"]
cwd = "./iepass-calib"
env.RUSTUP_TOOLCHAIN = "esp"
command = "cargo"
args = ["run", "${@}"]


# Build
[tasks.build]
dependencies = ["build-assets", "build-iepass", "build-calib"]
command = "cargo"
args = ["build", "--workspace", "--exclude", "iepass", "--exclude", "iepass-calib", "${@}"]

[tasks.build-assets]
cwd = "./assets"
command = "cargo"
args = ["make", "build", "${@}"]

[tasks.build-iepass]
cwd = "./iepass"
env.RUSTUP_TOOLCHAIN = "esp"
command = "cargo"
args = ["build", "${@}"]

[tasks.build-calib]
cwd = "./iepass-calib"
env.RUSTUP_TOOLCHAIN = "esp"
command = "cargo"
args = ["build", "${@}"]


# Clean Up
[tasks.clean]
dependencies = ["clean-assets"]
command = "git"
args = ["clean", "-Xdff", "--exclude=.idea", "${@}"]

[tasks.clean-assets]
cwd = "./assets"
command = "cargo"
args = ["make", "clean", "${@}"]


# Abstract
[tasks.script-base]
script_runner = "@rust"
script_runner_args = ["--base-path", "${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/scripts"]
