[config]
skip_core_tasks = true
default_to_workspace = false
unstable_features = ["CTRL_C_HANDLING"]


# Scripts
[tasks.rle-encode]
extend = "script-rs"
env.SCRIPT = "rle-encode"

[tasks.rle-decode]
extend = "script-rs"
env.SCRIPT = "rle-decode"

[tasks.font-gen]
extend = "script-rs"
env.SCRIPT = "font-gen"

[tasks.gif-gen]
extend = "script-rs"
env.SCRIPT = "gif-gen"

[tasks.numbers]
extend = "script-rs"
env.SCRIPT = "numbers"

[tasks.plots]
extend = "script-py"
env.SCRIPT = "plots"

[tasks.perf-probe-rs]
extend = "script-rs"
env.SCRIPT = "perf-probe-rs"


# Testing
[tasks.test]
dependencies = ["build-assets"]
command = "cargo"
args = ["test", "--workspace", "--exclude", "iepass", "--exclude", "iepass-calib", "${@}"]

[tasks.test-carts]
cwd = "./p8rs-tests"
command = "cargo"
args = ["test", "${@}"]

[tasks.test-ci]
dependencies = ["build-assets"]
command = "cargo"
args = ["test", "--workspace", "--exclude", "iepass", "--exclude", "iepass-calib", "--exclude", "p8rs-tests", "${@}"]

# Running
[tasks.run]
dependencies = ["build-assets"]
command = "cargo"
args = ["run", "--package", "iepass-emu", "${@}"]

[tasks.flash]
dependencies = ["build-assets"]
cwd = "./iepass"
env.RUSTUP_TOOLCHAIN = "esp"
command = "cargo"
args = ["run", "${@}"]

[tasks.flash-calib]
dependencies = ["build-assets"]
cwd = "./iepass-calib"
env.RUSTUP_TOOLCHAIN = "esp"
command = "cargo"
args = ["run", "${@}"]


# Build
[tasks.build]
dependencies = ["build-assets", "build-iepass", "build-calib"]
command = "cargo"
args = ["build", "--workspace", "--exclude", "iepass", "--exclude", "iepass-calib", "${@}"]

[tasks.build-assets]
cwd = "./assets"
command = "cargo"
args = ["make", "build", "${@}"]

[tasks.build-iepass]
cwd = "./iepass"
env.RUSTUP_TOOLCHAIN = "esp"
command = "cargo"
args = ["build", "${@}"]

[tasks.build-calib]
cwd = "./iepass-calib"
env.RUSTUP_TOOLCHAIN = "esp"
command = "cargo"
args = ["build", "${@}"]


# Clean Up
[tasks.clean]
dependencies = ["clean-assets"]
command = "git"
args = ["clean", "-Xdff", "--exclude=.idea", "${@}"]

[tasks.clean-assets]
cwd = "./assets"
command = "cargo"
args = ["make", "clean", "${@}"]


# Abstract
[tasks.script-rs]
command = "cargo"
args = ["run", "--package", "scripts", "--bin", "${SCRIPT}", "--", "${@}"]

[tasks.script-py]
command = "python"
args = ["scripts/${SCRIPT}.py", "${@}"]
