[package]
name     = "iepass-calib"
resolver = "3"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[[bin]]
name = "iepass-test"
path = "src/main.rs"
test = false

[dependencies]
p8rs = { workspace = true, features = ["defmt"] }
p8rs-log = { workspace = true, features = ["defmt"] }
iepass.workspace = true
anyhow.workspace = true
defmt.workspace = true
esp-bootloader-esp-idf.workspace = true
esp-alloc.workspace = true
esp-hal.workspace = true
esp-rtos.workspace = true
embassy-executor.workspace = true
embassy-time.workspace = true
embedded-io.workspace = true
embedded-hal-async.workspace = true
embassy-futures.workspace = true
rtt-target.workspace = true
panic-rtt-target.workspace = true
