[package]
name          = "iepass"
version       = "0.1.0"
authors       = ["Fun Maker <funmaker95@gmail.com>"]
edition       = "2024"
resolver      = "3"
rust-version  = "1.88.0"

[[bin]]
name = "iepass"
path = "src/main.rs"
test = false

[[test]]
name    = "hello_test"
harness = false

[lib]
name = "iepass"
test = false

[features]
default = ["perf"]
perf = ["esp-alloc/internal-heap-stats"]

[dependencies]
iepass-core = { workspace = true, features = ["defmt"] }
anyhow = { workspace = true }
defmt = { workspace = true }
esp-bootloader-esp-idf = { workspace = true }
esp-alloc = { workspace = true }
esp-hal = { workspace = true }
esp-hal-embassy = { workspace = true }
embassy-executor = { workspace = true }
embassy-time = { workspace = true }
embassy-sync = { workspace = true }
embassy-embedded-hal = { workspace = true }
embedded-hal-async = { workspace = true }
embedded-io = { workspace = true }
rtt-target = { workspace = true }
panic-rtt-target = { workspace = true }
ringbuffer = { workspace = true }
pin-project = { workspace = true }
static_cell = { workspace = true }
nb = { workspace = true }
bitflags = { workspace = true }

[dev-dependencies]
embedded-test = { version = "0.6.0", features = [
  "defmt",
  "embassy",
  "external-executor",
  "xtensa-semihosting",
] }
