[package]
name     = "p8rs"
resolver = "3"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[features]
default = ["std"]
std = ["p8rs-piccolo/std", "embedded-io/std"]
defmt = ["p8rs-piccolo/defmt", "dep:defmt"]
log-04 = ["p8rs-piccolo/log-04"]

[dependencies]
defmt = { workspace = true, optional = true }
p8rs-log.workspace = true
p8rs-piccolo.workspace = true
p8rs-types = { workspace = true, features = ["bytemuck"] }
p8rs-macros.workspace = true
embedded-io.workspace = true
gc-arena.workspace = true
anyhow.workspace = true
bitflags.workspace = true
thiserror.workspace = true
bytemuck.workspace = true

[dev-dependencies]
embedded-io.workspace = true
