[package]
name     = "p8rs-macros"
resolver = "3"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[lib]
proc-macro = true

[dependencies]
p8rs-types.workspace = true
quote = "1.0.41"
syn = "2.0.106"
proc-macro2 = "1.0.95"
