[package]
name          = "iepass-core"
version       = "0.1.0"
authors       = ["Fun Maker <funmaker95@gmail.com>"]
edition       = "2024"
resolver      = "3"
rust-version  = "1.88.0"

[features]
std = ["embedded-io/std"]
defmt = ["dep:defmt"]
log-04 = ["dep:log-04"]

[dependencies]
cfg-if = { version = "1.0.3" }
log-04 = { package = "log", version = "0.4.27", optional = true }
embedded-io = { workspace = true }
defmt = { workspace = true, optional = true }
piccolo = { workspace = true }
micromath = { workspace = true }
gc-arena = "0.5.3"
bitflags = "1.3.2"

[dev-dependencies]
embedded-io = { workspace = true }
