[package]
name     = "iepass-core"
resolver = "3"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[features]
std = ["embedded-io/std"]
defmt = ["dep:defmt", "p8rs-types/defmt"]
log-04 = ["dep:log-04"]

[dependencies]
cfg-if = { version = "1.0.3" }
log-04 = { package = "log", version = "0.4.27", optional = true }
embedded-io.workspace = true
defmt = { workspace = true, optional = true }
p8rs-piccolo.workspace = true
p8rs-types.workspace = true
p8rs-macros.workspace = true
micromath.workspace = true
bitflags.workspace = true
thiserror.workspace = true

[dev-dependencies]
embedded-io.workspace = true
