[package]
name     = "p8rs-types"
resolver = "3"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[features]
gc-arena = ["dep:gc-arena"]
defmt = ["dep:defmt"]

[dependencies]
arrayvec.workspace = true
thiserror.workspace = true
bitflags.workspace = true
gc-arena = { workspace = true, optional = true }
defmt = { workspace = true, optional = true }
