[config]
skip_core_tasks = true


# Clean
[tasks.clean]
command = "git"
args = ["clean", "-Xdff", "${@}"]


# Build
[tasks.build]
dependencies = [
    "build-BadApple",
    "build-XD",
    "build-calib1",
    "build-calib2",
    "build-calib3",
    "build-calib4",
    "build-calib5",
    "build-calib-target",
    "build-kutasan",
    "build-font",
]

[tasks.build-BadApple]
extend = "rle"
env.ASSET_NAME = "BadApple"
condition = { files_modified = { input = ["assets/BadApple.raw"], output = ["assets/BadApple.smol"] } }

[tasks.build-XD]
extend = "rle"
env.ASSET_NAME = "XD"
condition = { files_modified = { input = ["assets/XD.raw"], output = ["assets/XD.smol"] } }

[tasks.build-calib1]
dependencies = ["build-calib1-raw"]
extend = "rle"
env.ASSET_NAME = "calib1"
condition = { files_modified = { input = ["assets/calib1.raw"], output = ["assets/calib1.smol"] } }

[tasks.build-calib1-raw]
extend = "png-rgb565"
env.ASSET_NAME = "calib1"
condition = { files_modified = { input = ["calib1.png"], output = ["calib1.raw"] } }

[tasks.build-calib2]
dependencies = ["build-calib2-raw"]
extend = "rle"
env.ASSET_NAME = "calib2"
condition = { files_modified = { input = ["assets/calib2.raw"], output = ["assets/calib2.smol"] } }

[tasks.build-calib2-raw]
extend = "png-rgb565"
env.ASSET_NAME = "calib2"
condition = { files_modified = { input = ["calib2.png"], output = ["calib2.raw"] } }

[tasks.build-calib3]
dependencies = ["build-calib3-raw"]
extend = "rle"
env.ASSET_NAME = "calib3"
condition = { files_modified = { input = ["assets/calib3.raw"], output = ["assets/calib3.smol"] } }

[tasks.build-calib3-raw]
extend = "png-rgb565"
env.ASSET_NAME = "calib3"
condition = { files_modified = { input = ["calib3.png"], output = ["calib3.raw"] } }

[tasks.build-calib4]
dependencies = ["build-calib4-raw"]
extend = "rle"
env.ASSET_NAME = "calib4"
condition = { files_modified = { input = ["assets/calib4.raw"], output = ["assets/calib4.smol"] } }

[tasks.build-calib4-raw]
extend = "png-rgb565"
env.ASSET_NAME = "calib4"
condition = { files_modified = { input = ["calib4.png"], output = ["calib4.raw"] } }

[tasks.build-calib5]
dependencies = ["build-calib5-raw"]
extend = "rle"
env.ASSET_NAME = "calib5"
condition = { files_modified = { input = ["assets/calib5.raw"], output = ["assets/calib5.smol"] } }

[tasks.build-calib5-raw]
extend = "png-rgb565"
env.ASSET_NAME = "calib5"
condition = { files_modified = { input = ["calib5.png"], output = ["calib5.raw"] } }

[tasks.build-calib-target]
dependencies = ["build-calib-target-raw"]
extend = "rle"
env.ASSET_NAME = "calib-target"
condition = { files_modified = { input = ["assets/calib-target.raw"], output = ["assets/calib-target.smol"] } }

[tasks.build-calib-target-raw]
extend = "png-rgb565"
env.ASSET_NAME = "calib-target"
condition = { files_modified = { input = ["calib-target.png"], output = ["calib-target.raw"] } }

[tasks.build-kutasan]
extend = "wav-pcm"
env.ASSET_NAME = "kutasan"
condition = { files_modified = { input = ["kutasan.wav"], output = ["kutasan.pcm"] } }

[tasks.build-font]
cwd = ".."
command = "cargo"
args = ["make", "font-gen", "assets/font.png", "p8rs/src/pico8/font/generated.rs"]
condition = { files_modified = { input = ["assets/font.png"], output = ["p8rs/src/vm/font/generated.rs"] } }


# Abstract
[tasks.rle]
cwd = ".."
command = "cargo"
args = ["make", "rle-encode", "assets/${ASSET_NAME}.raw", "assets/${ASSET_NAME}.smol"]

[tasks.png-rgb565]
command = "ffmpeg"
args = ["-i", "${ASSET_NAME}.png", "-vcodec", "rawvideo", "-f", "rawvideo", "-pix_fmt", "rgb565be", "${ASSET_NAME}.raw", "-y"]

[tasks.wav-pcm]
command = "ffmpeg"
args = ["-i", "${ASSET_NAME}.wav", "-ar", "44100", "-ac", "1", "-af", "volume=0.1", "-f", "s16le", "-acodec", "pcm_s16le", "${ASSET_NAME}.pcm", "-y"]
