[package]
name     = "iepass-emu"
resolver = "3"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
eframe = "0.32.0"
egui = "0.32.0"
iepass-core = { workspace = true, features = ["std"] }
    