[package]
name     = "iepass-emu"
resolver = "3"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[features]
default = ["log-04"]
log-04 = ["p8rs/log-04", "p8rs-log/log-04"]

[dependencies]
p8rs = { workspace = true, features = ["std", "rand"] }
p8rs-log = { workspace = true, features = ["std"] }
p8rs-types.workspace = true
env_logger.workspace = true
eframe = "0.33.2"
egui = "0.33.2"
