[package]
name     = "iepass-emu"
resolver = "3"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[features]
default = ["p8rs-log/log-04"]

[dependencies]
p8rs-log.workspace = true
p8rs = { workspace = true, features = ["std"] }
eframe = "0.33.2"
egui = "0.33.2"
    