pico-8 cartridge // http://www.pico-8.com
version 43

__lua__
p8rs.test("█", █)
p8rs.test("▒", ▒)
p8rs.test("🐱", 🐱)
p8rs.test("⬇️", ⬇️)
p8rs.test("░", ░)
p8rs.test("✽", ✽)
p8rs.test("●", ●)
p8rs.test("♥", ♥)
p8rs.test("☉", ☉)
p8rs.test("웃", 웃)
p8rs.test("⌂", ⌂)
p8rs.test("⬅️", ⬅️)
p8rs.test("😐", 😐)
p8rs.test("♪", ♪)
p8rs.test("🅾️", 🅾️)
p8rs.test("◆", ◆)
p8rs.test("…", …)
p8rs.test("➡️", ➡️)
p8rs.test("★", ★)
p8rs.test("⧗", ⧗)
p8rs.test("⬆️", ⬆️)
p8rs.test("ˇ", ˇ)
p8rs.test("∧", ∧)
p8rs.test("❎", ❎)
p8rs.test("▤", ▤)
p8rs.test("▥", ▥)
