name: Tests

on:
  push:
    branches:
      - master
    paths-ignore:
      - "**/README.md"
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  rust-checks:
    name: Rust Checks
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout
        uses: actions/checkout@v4
      - name: 📥 Setup Rust
        uses: esp-rs/xtensa-toolchain@v1.5
        with:
          default: false
          buildtargets: esp32s3
          ldproxy: false
          version: '1.90.0'
      - name: 📥 Install Dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y --no-install-recommends libasound2-dev
          rustup default nightly-2025-09-01
          cargo install cargo-make
      - name: 🎥 FFmpeg Setup
        uses: FedericoCarboni/setup-ffmpeg@v3
      - name: 🛢 Cache
        uses: Swatinem/rust-cache@v2
      - name: 🔨 Build project
        run: cargo make build
      - name: 🧪 Run tests
        run: cargo make test
