name: Tests

on:
  push:
    branches:
      - master
    paths-ignore:
      - "../../README.md"
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  rust-checks:
    name: Rust Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo
            ~/.rustup
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Install Dependencies
        run: |
          rustup override set nightly
          cargo install cargo-make rust-script
          # cargo install espup ldproxy
          # espup install --targets=esp32,esp32s2,esp32s3
      - name: Build project
        run: cargo make build
      - name: Run tests
        run: cargo make test
